Dolor: /Users/mark/Documents/CLASS/#SVN/dolor/dolor/trunk/src/main.cpp File Reference
/Users/mark/Documents/CLASS/#SVN/dolor/dolor/trunk/src/main.cpp File Reference
#include <iostream>
#include <fstream>
#include <string>
#include "inc/set_of_books.h"
#include "inc/Category.h"
#include "inc/lib/tinyxml/tinyxml.h"
Functions
void displayMenu ()
void doWork (int)
void displayBookMenu ()
void doBookWork (int)
int main ()
Variables
Books book ("test","test")
Function Documentation
void displayBookMenu ()
Definition at line 159 of file main.cpp.
Referenced by doBookWork(), and doWork().
void displayMenu ()
Definition at line 216 of file main.cpp.
References doWork().
Referenced by doBookWork(), doWork(), and main().
void doBookWork (int answer)
Definition at line 88 of file main.cpp.
References Books::addSubCat(), book, displayBookMenu(), displayMenu(), Books::insertAccountByHand(), Books::listAccounts(), Books::listCat(), and Books::openAccount().
void doWork (int answer)
Definition at line 232 of file main.cpp.
References book, displayBookMenu(), displayMenu(), Books::read(), and Books::write().
Referenced by displayMenu().
int main ()
Definition at line 284 of file main.cpp.
References displayMenu().
Variable Documentation
Books book("test","test")
Referenced by doBookWork(), and doWork().